apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mit-kerberos.fullname" . }}
  labels:
    app: {{ include "mit-kerberos.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mit-kerberos.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mit-kerberos.name" . }}
    spec:
      containers:
        - name: mit-kerberos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REALM
              value: "{{ .Values.env.REALM }}"
            - name: KDC_HOST_ADDRESS
              value: "{{ .Values.env.KDC_HOST_ADDRESS }}"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secret.useExisting }}{{ .Values.secret.name }}{{ else }}{{ include "mit-kerberos.fullname" . }}-secret{{ end }}
                  key: {{ .Values.secret.key }}

          ports:
            - containerPort: {{ .Values.service.ports.kdc }}
              name: kdc
            - containerPort: {{ .Values.service.ports.admin }}
              name: admin
          volumeMounts:
            - name: krb5db
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: krb5db
          persistentVolumeClaim:
            claimName: krb5db-pvc

