{{- if not .Values.secret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mit-kerberos.fullname" . }}-secret
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.env.ADMIN_PASSWORD | b64enc | quote }}
{{- end }}
