apiVersion: v1
kind: Service
metadata:
  name: {{ include "mit-kerberos.fullname" . }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  ports:
    - name: kdc
      port: {{ .Values.service.ports.kdc }}
      targetPort: kdc
    - name: admin
      port: {{ .Values.service.ports.admin }}
      targetPort: admin
  selector:
    app: {{ include "mit-kerberos.name" . }}
